<a href="https://colab.research.google.com/github/itimes-digital/deep-learning-estudo/blob/main/estudo_tensorflow_v4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [ ]:
!pip install tensorflow==1.14
!pip install tensorflow

In [3]:
a = tf.constant([[1,2], [3,4]])
b = tf.constant([[-1,3], [4,2]])

In [4]:
multiplicacao = tf.matmul(a, b)

## A multiplicação de matrizes ocorrem com os dados da linha da primeira matriz com a coluna da segunda matriz.
# 1 * (-1) + 2 * 4 = **7** | 1 * 3 + 2 * 2 = **7** | ...

In [6]:
with tf.Session() as sess:
    print(sess.run(a))
    print('\n')
    print(sess.run(b))
    print('\n')
    print(sess.run(multiplicacao))

[[1 2]
 [3 4]]


[[-1  3]
 [ 4  2]]


[[ 7  7]
 [13 17]]


In [7]:
multiplicacao2 = tf.matmul(b, a)

In [9]:
with tf.Session() as sess:
    print(sess.run(multiplicacao2))

[[ 8 10]
 [10 16]]


In [11]:
a1 = tf.constant([[2,3], [0,1], [-1,4]])
b1 = tf.constant([[1,2,3], [-2,0,4]])
multiplicacao3 = tf.matmul(a1, b1)

# 2 * 1 + 3 * (-2) = **-4** | 2 * 2 + 3 * 0 = **4** | 2 * 3 + 3 * 4 = **18** | ...

In [12]:
with tf.Session() as sess:
    print(sess.run(a1))
    print('\n')
    print(sess.run(b1))
    print('\n')
    print(sess.run(multiplicacao3))

[[ 2  3]
 [ 0  1]
 [-1  4]]


[[ 1  2  3]
 [-2  0  4]]


[[-4  4 18]
 [-2  0  4]
 [-9 -2 13]]
