<a href="https://colab.research.google.com/github/itimes-digital/deep-learning-estudo/blob/main/estudo_tensorflow_v3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import tensorflow as tf

In [2]:
tf.__version__

'1.14.0'

In [ ]:
!pip install tensorflow==1.14
!pip install tensorflow

In [4]:
x = 35
y = x + 35

In [5]:
print(y)

70


In [6]:
valor1 = tf.constant(15, name = 'valor1')
print(valor1)

Tensor("valor1:0", shape=(), dtype=int32)


In [7]:
soma = tf.Variable(valor1 + 5, name = 'valor1')

In [8]:
print(soma)
type(soma)

<tf.Variable 'valor1_1:0' shape=() dtype=int32_ref>


tensorflow.python.ops.variables.RefVariable

In [9]:
init = tf.global_variables_initializer()

In [10]:
with tf.Session() as sess:
  sess.run(init)
  print(sess.run(soma))

20


In [11]:
vetor = tf.constant([5,10,15], name = 'vetor')

In [12]:
type(vetor)

tensorflow.python.framework.ops.Tensor

In [13]:
print(vetor)

Tensor("vetor:0", shape=(3,), dtype=int32)


In [14]:
soma = tf.Variable(vetor + 5, name = 'soma')

In [15]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  print(sess.run(soma))

[10 15 20]


In [16]:
valor = tf.Variable(0, name = 'valor')

In [17]:
print(valor)

<tf.Variable 'valor:0' shape=() dtype=int32_ref>


In [18]:
init2 = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init2)
  for i in range(5):
    valor = valor + 1
    print(sess.run(valor))

1
2
3
4
5


In [20]:
a2 = tf.constant([[1,2,3],[4,5,6]])
b2 = tf.constant([[1], [2]])

In [21]:
with tf.Session() as sess:
    print(sess.run(a2))
    print('\n')
    print(sess.run(b2))
    print('\n')

[[1 2 3]
 [4 5 6]]


[[1]
 [2]]




In [22]:
soma2 = tf.add(a2, a2)

In [23]:
with tf.Session() as sess:
    print(sess.run(a2))
    print('\n')
    print(sess.run(b2))
    print('\n')
    print(sess.run(soma2))

[[1 2 3]
 [4 5 6]]


[[1]
 [2]]


[[ 2  4  6]
 [ 8 10 12]]
