<a href="https://colab.research.google.com/github/itimes-digital/deep-learning-estudo/blob/main/recomendacao_rbm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from sample_data.rbm import RBM
import pandas as pd
import numpy as np

In [10]:
rbm = RBM(num_visible = 6, num_hidden = 2) # números de variáveis e números de neurônios

In [11]:
base = np.array([
                 [1,1,1,0,0,0],
                 [1,0,1,0,0,0],
                 [1,1,1,0,0,0],
                 [0,0,1,1,1,1],
                 [0,0,1,1,0,1],
                 [0,0,1,1,0,1]
                 ])
base.shape

(6, 6)

In [ ]:
rbm.train(base, max_epochs = 5000)

In [13]:
rbm.weights

array([[ 2.46989278,  2.31518867,  0.36075925],
       [-1.00909476, -3.29466918,  7.94699695],
       [ 0.24110822, -7.27332248,  3.31778718],
       [ 4.94687576,  3.88567373,  1.87058209],
       [ 0.95170234,  3.62262235, -8.23437603],
       [-1.31621241,  0.61144478, -4.55005251],
       [ 0.95685855,  3.61867643, -8.23694571]])

In [35]:
usuario_1 = np.array([[1,1,0,1,0,0]])

In [36]:
rbm.run_visible(usuario_1)

array([[0., 1.]])

In [56]:
usuario_2 = np.array([[0,0,0,1,1,0]])

In [57]:
rbm.run_visible(usuario_2)

array([[1., 0.]])

In [50]:
usuario_3 = np.array([[1,1,0,0,1,1]])

In [51]:
rbm.run_visible(usuario_3)

array([[0., 0.]])

In [58]:
camada_escondida = np.array([[1,0]])

In [59]:
recomendacao = rbm.run_hidden(camada_escondida)
recomendacao

array([[0., 0., 1., 1., 0., 1.]])

In [54]:
filmes = ['A Bruxa', 'Invocação do Mal', 'O Chamado', 'Se beber não case', 'Gente Grande', 'American Pie']

In [60]:
for i in range(len(usuario_2[0])):
  #print(usuario_1[0, i])
  if usuario_2[0, i] == 0 and recomendacao[0, i] == 1:
    print(filmes[i])

O Chamado
American Pie
