<a href="https://colab.research.google.com/github/itimes-digital/deep-learning-estudo/blob/main/recomendacao_filmes_rbm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Restricted Boltzmann Machine para recomendação de filmes

In [37]:
import pandas as pd
import numpy as np
from sample_data.rbm import RBM

In [38]:
base = np.array([['Ana', 0, 1, 1, 1, 0, 1],
               ['Marcos', 1, 1, 0, 1, 1, 1],
               ['Pedro', 0, 1, 0, 1, 0, 1],
               ['Claudia', 0, 1, 1, 1, 0, 1],
               ['Adriano', 1, 1, 0, 1, 0, 1],
               ['Janaina', 1, 1, 0, 1, 1, 1]
               ])

In [39]:
base_filmes = pd.DataFrame(data = base, columns = ['usuario', 
                                                   'Freddy x Jason', 
                                                   'O Ultimato Bourne',
                                                   'Star Trek',
                                                   'Exterminador do Futuro',
                                                   'Norbit',
                                                   'Star Wars']);

In [40]:
base_filmes.head(10)

usuario Freddy x Jason  ... Norbit Star Wars
0      Ana              0  ...      0         1
1   Marcos              1  ...      1         1
2    Pedro              0  ...      0         1
3  Claudia              0  ...      0         1
4  Adriano              1  ...      0         1
5  Janaina              1  ...      1         1

[6 rows x 7 columns]

In [41]:
base_filmes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   usuario                 6 non-null      object
 1   Freddy x Jason          6 non-null      object
 2   O Ultimato Bourne       6 non-null      object
 3   Star Trek               6 non-null      object
 4   Exterminador do Futuro  6 non-null      object
 5   Norbit                  6 non-null      object
 6   Star Wars               6 non-null      object
dtypes: object(7)
memory usage: 464.0+ bytes


In [42]:
base_filmes['Freddy x Jason'] = pd.to_numeric(base_filmes['Freddy x Jason']);
base_filmes['O Ultimato Bourne'] = pd.to_numeric(base_filmes['O Ultimato Bourne']);
base_filmes['Star Trek'] = pd.to_numeric(base_filmes['Star Trek']);
base_filmes['Exterminador do Futuro'] = pd.to_numeric(base_filmes['Exterminador do Futuro']);
base_filmes['Norbit'] = pd.to_numeric(base_filmes['Norbit']);
base_filmes['Star Wars'] = pd.to_numeric(base_filmes['Star Wars']);
base_filmes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   usuario                 6 non-null      object
 1   Freddy x Jason          6 non-null      int64 
 2   O Ultimato Bourne       6 non-null      int64 
 3   Star Trek               6 non-null      int64 
 4   Exterminador do Futuro  6 non-null      int64 
 5   Norbit                  6 non-null      int64 
 6   Star Wars               6 non-null      int64 
dtypes: int64(6), object(1)
memory usage: 464.0+ bytes


In [43]:
rbm = RBM(num_visible = 6, num_hidden = 3) # nós que são neurônios conectados

In [ ]:
rbm.train(base_filmes.iloc[:, 1:7].values, max_epochs = 5000);

In [45]:
rbm.weights

array([[ 0.84152207, -1.10812229, -1.03651273, -0.08773828],
       [ 1.61611282,  1.72625612,  1.83242586, -7.73567437],
       [ 3.58855331,  1.21646777,  1.2554566 ,  1.68330849],
       [-0.42093041, -5.43602546, -5.64018251,  5.87301679],
       [ 3.59267023,  1.24588889,  1.20198203,  1.70731328],
       [ 0.0722511 ,  0.32859366,  0.36202037, -5.87561671],
       [ 3.6158447 ,  1.20604382,  1.23635204,  1.66498255]])

In [55]:
usuario_leonardo = np.array([[0, 1, 0, 1, 0, 0]])

In [79]:
camada_escondida = rbm.run_visible(usuario_leonardo)
camada_escondida

array([[1., 0., 0.]])

In [80]:
recomendacao = rbm.run_hidden(camada_escondida)
recomendacao

array([[1., 1., 0., 1., 0., 1.]])

In [81]:
base_filmes.head(10)

usuario  Freddy x Jason  ...  Norbit  Star Wars
0      Ana               0  ...       0          1
1   Marcos               1  ...       1          1
2    Pedro               0  ...       0          1
3  Claudia               0  ...       0          1
4  Adriano               1  ...       0          1
5  Janaina               1  ...       1          1

[6 rows x 7 columns]

In [82]:
base_filmes.columns

Index(['usuario', 'Freddy x Jason', 'O Ultimato Bourne', 'Star Trek',
       'Exterminador do Futuro', 'Norbit', 'Star Wars'],
      dtype='object')

In [83]:
filmes = ['Freddy x Jason', 'O Ultimato Bourne', 'Star Trek',
       'Exterminador do Futuro', 'Norbit', 'Star Wars']

In [84]:
for i in range(len(usuario_leonardo[0])):
  #print(usuario_1[0, i])
  if usuario_leonardo[0, i] == 0 and recomendacao[0, i] == 1:
    print(filmes[i])

Freddy x Jason
Star Wars
