<a href="https://colab.research.google.com/github/itimes-digital/deep-learning-estudo/blob/main/classificacao_binaria_simples_breast_cancer_analise_layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
previsores = pd.read_csv("https://raw.githubusercontent.com/itimes-digital/deep-learning-estudo/main/dataset/entradas_breast.csv", sep=",")
previsores.head()

radius_mean   texture_mean  ...   symmetry_worst   fractal_dimension_worst
0         17.99          10.38  ...           0.4601                   0.11890
1         20.57          17.77  ...         275.0000                   0.08902
2         19.69          21.25  ...           0.3613                   0.08758
3         11.42          20.38  ...           0.6638                 173.00000
4         20.29          14.34  ...           0.2364                   0.07678

[5 rows x 30 columns]

In [3]:
previsores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0    radius_mean              569 non-null    float64
 1    texture_mean             569 non-null    float64
 2    perimeter_mean           569 non-null    float64
 3    area_mean                569 non-null    float64
 4    smoothness_mean          569 non-null    float64
 5    compactness_mean         569 non-null    float64
 6    concavity_mean           569 non-null    float64
 7   concave_points_mean       569 non-null    float64
 8    symmetry_mean            569 non-null    float64
 9    fractal_dimension_mean   569 non-null    float64
 10   radius_se                569 non-null    float64
 11   texture_se               569 non-null    float64
 12   perimeter_se             569 non-null    float64
 13   area_se                  569 non-null    float64
 14   smoothnes

In [4]:
classe = pd.read_csv("https://raw.githubusercontent.com/itimes-digital/deep-learning-estudo/main/dataset/saidas_breast.csv")
classe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       569 non-null    int64
dtypes: int64(1)
memory usage: 4.6 KB


In [16]:
classe.head()

0
0  0
1  0
2  0
3  0
4  0

In [5]:
from sklearn.model_selection import train_test_split

# previsores_treinamento = x_train
# previsores_teste = x_test
# classe_treinamento = y_train
# classe_teste = y_test
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, 
                                                                                              classe, 
                                                                                              test_size = 0.25)

In [18]:
previsores_treinamento.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 426 entries, 156 to 193
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0    radius_mean              426 non-null    float64
 1    texture_mean             426 non-null    float64
 2    perimeter_mean           426 non-null    float64
 3    area_mean                426 non-null    float64
 4    smoothness_mean          426 non-null    float64
 5    compactness_mean         426 non-null    float64
 6    concavity_mean           426 non-null    float64
 7   concave_points_mean       426 non-null    float64
 8    symmetry_mean            426 non-null    float64
 9    fractal_dimension_mean   426 non-null    float64
 10   radius_se                426 non-null    float64
 11   texture_se               426 non-null    float64
 12   perimeter_se             426 non-null    float64
 13   area_se                  426 non-null    float64
 14   smoothn

In [19]:
previsores_teste.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 143 entries, 307 to 424
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0    radius_mean              143 non-null    float64
 1    texture_mean             143 non-null    float64
 2    perimeter_mean           143 non-null    float64
 3    area_mean                143 non-null    float64
 4    smoothness_mean          143 non-null    float64
 5    compactness_mean         143 non-null    float64
 6    concavity_mean           143 non-null    float64
 7   concave_points_mean       143 non-null    float64
 8    symmetry_mean            143 non-null    float64
 9    fractal_dimension_mean   143 non-null    float64
 10   radius_se                143 non-null    float64
 11   texture_se               143 non-null    float64
 12   perimeter_se             143 non-null    float64
 13   area_se                  143 non-null    float64
 14   smoothn

In [20]:
classe_treinamento.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 426 entries, 156 to 193
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       426 non-null    int64
dtypes: int64(1)
memory usage: 6.7 KB


In [21]:
classe_teste.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 143 entries, 307 to 424
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       143 non-null    int64
dtypes: int64(1)
memory usage: 2.2 KB


In [10]:
import keras

In [11]:
from keras.models import Sequential
from keras.layers import Dense

Definição do números de neurônios por camada:

(numero de entrada + numero de saídas esperada) / 2 = número de units na camada.

In [12]:
# Medida base para definir a quantidade de neurônios na camada.
# Como a classificação é binária, a resposta será 0 ou 1, portanto, uma saída.
quantSaidaEsperada = 1
units = (previsores.columns.size + quantSaidaEsperada) / 2
units = np.round(units)
units

16.0

In [30]:
# input_dim define a quantidade de neurônios para a camada de entrada.
classificador = Sequential() # Estrutura básica para colocar as camadas sequencialmente
classificador.add(Dense(units=units, # define a quantidade de neurônios a camada oculta 
                        activation='relu', 
                        kernel_initializer='random_uniform', 
                        input_dim=30))

In [31]:
# Camada intermediária ou oculta
classificador.add(Dense(units=units, # define a quantidade de neurônios a camada oculta
                        activation='relu', 
                        kernel_initializer='random_uniform'))

In [32]:
# Definindo a camada de saída
# Como é um classificador binário para 0 ou 1
# A quantidade de neurônio é 1
classificador.add(Dense(units=1, activation="sigmoid"))

In [40]:
otimizador = keras.optimizers.Adam(lr=0.0001, decay = 0.00001, clipvalue = 0.5)

In [41]:
# para classificação binária deve usar binary_crossentropy
# para classificação com mais de duas classes deve usar categorical_crossentropy
classificador.compile(optimizer= otimizador, 
                      loss='binary_crossentropy',
                      metrics=['binary_accuracy'])
classificador.fit(previsores_treinamento, 
                  classe_treinamento,
                  batch_size=10, # Atualização de pesos a cada 10 registros por épocas
                  epochs=100)


Epoch 1/100
43/43 [==============================] - 0s 1ms/step - loss: 0.0942 - binary_accuracy: 0.9624
Epoch 2/100
43/43 [==============================] - 0s 1ms/step - loss: 0.0939 - binary_accuracy: 0.9507
Epoch 3/100
43/43 [==============================] - 0s 1ms/step - loss: 0.0901 - binary_accuracy: 0.9577
Epoch 4/100
43/43 [==============================] - 0s 1ms/step - loss: 0.0906 - binary_accuracy: 0.9577
Epoch 5/100
43/43 [==============================] - 0s 1ms/step - loss: 0.0923 - binary_accuracy: 0.9601
Epoch 6/100
43/43 [==============================] - 0s 1ms/step - loss: 0.0907 - binary_accuracy: 0.9624
Epoch 7/100
43/43 [==============================] - 0s 1ms/step - loss: 0.0858 - binary_accuracy: 0.9554
Epoch 8/100
43/43 [==============================] - 0s 1ms/step - loss: 0.0889 - binary_accuracy: 0.9554
Epoch 9/100
43/43 [==============================] - 0s 1ms/step - loss: 0.0894 - binary_accuracy: 0.9554
Epoch 10/100
43/43 [==========================

In [66]:
# Pega os pesos das camadas
peso0 = classificador.layers[0].get_weights()
len(peso0)

2

In [67]:
# Pesos da primeira camada
peso0[0]

array([[ 6.84672035e-03, -6.12504296e-02, -5.66951036e-02,
        -3.40000242e-02, -2.31132284e-02, -1.33959800e-01,
        -3.67320478e-02,  3.84917744e-02, -1.04008345e-02,
         1.05691865e-01,  1.20313406e-01,  1.48824200e-01,
         1.94278806e-01,  6.78036138e-02,  3.61270760e-03,
         2.79462766e-02],
       [ 7.55902976e-02,  9.38729965e-04, -1.39848337e-01,
        -4.69592325e-02, -1.86356227e-03,  1.43710226e-01,
        -2.68873349e-02, -3.31363194e-02, -6.57269806e-02,
         1.84019551e-01, -3.98956463e-02, -1.11075491e-02,
        -1.89867038e-02,  4.00250293e-02, -5.84036522e-02,
         2.20136251e-02],
       [ 5.60307652e-02, -2.57828441e-02, -1.51256338e-01,
         1.25720903e-01,  6.33857492e-03, -1.77797720e-01,
        -4.41979319e-02, -2.92504188e-02, -8.59002843e-02,
         1.01691112e-01,  1.51548937e-01,  1.68153182e-01,
         2.01008797e-01,  7.77145848e-02, -1.34202108e-01,
        -2.15154141e-01],
       [ 6.91713095e-02, -2.33585164e

In [68]:
# Na segunda posição do array é o bias
peso0[1]

array([ 0.11646228,  0.00048785, -0.24376181,  0.27339286,  0.02465107,
       -0.33949623,  0.0424988 , -0.0048613 , -0.04206857,  0.23752463,
        0.30821288,  0.37126327,  0.47610372,  0.15448952, -0.3491589 ,
       -0.4320303 ], dtype=float32)

In [69]:
peso1 = classificador.layers[1].get_weights()
len(peso1)

2

In [70]:
peso1[0]

array([[ 2.90444549e-02,  3.62366326e-02, -4.75799702e-02,
        -2.02963706e-02,  2.30402928e-02,  1.80412009e-01,
         5.11377789e-02,  6.33499306e-03,  5.48842065e-02,
         1.53404884e-02,  4.39832918e-02,  4.94176662e-03,
        -1.91787519e-02,  3.78676243e-02,  1.59984782e-01,
         7.98290297e-02],
       [-5.17217442e-02, -3.23301814e-02,  5.39864367e-03,
        -2.68607140e-02, -8.75708908e-02,  2.29307972e-02,
        -6.17160685e-02, -7.69369155e-02,  2.84438618e-02,
        -9.98429209e-02,  5.75968772e-02,  1.15862533e-01,
        -4.18278836e-02,  1.10133909e-01,  2.76917387e-02,
        -1.65302232e-02],
       [ 1.47392815e-02, -9.45309177e-02, -9.46876928e-02,
        -4.07741368e-02,  6.48661926e-02, -1.20679513e-01,
        -7.53533691e-02, -6.56420514e-02, -6.88803047e-02,
         5.83877079e-02,  4.12291810e-02,  1.59376729e-02,
        -4.93434519e-02,  2.61324588e-02, -1.06887177e-01,
        -1.27931625e-01],
       [ 2.71548890e-02,  3.69830020e

In [71]:
peso1[1]

array([-0.31922436,  0.28839153, -0.04222861, -0.13052233, -0.42143473,
        0.08872291,  0.41554144,  0.39655325,  0.03314235, -0.33132392,
        0.35860404,  0.3503672 ,  0.23331279,  0.34602228,  0.10022593,
        0.27161685], dtype=float32)

In [72]:
peso2 = classificador.layers[2].get_weights()
len(peso2)

2

In [73]:
peso2[0]

array([[-0.5286843 ],
       [ 0.09075686],
       [-0.18509465],
       [-0.28132325],
       [-0.5515023 ],
       [ 0.3331244 ],
       [ 0.35991105],
       [ 0.32899803],
       [ 0.09291659],
       [-0.37774086],
       [ 0.3212055 ],
       [ 0.12057946],
       [ 0.1976873 ],
       [ 0.41233402],
       [ 0.4034809 ],
       [ 0.45659557]], dtype=float32)

In [74]:
peso2[1]

array([0.33651152], dtype=float32)

In [76]:
previsoes = classificador.predict(previsores_teste)
previsoes = (previsoes > 0.5)

In [77]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [78]:
precisao = accuracy_score(classe_teste, previsoes)
precisao

0.916083916083916

In [45]:
matriz_confusao = confusion_matrix(classe_teste, previsoes)
matriz_confusao

array([[52,  3],
       [ 9, 79]])

In [46]:
# Usando o Keras
resultado = classificador.evaluate(previsores_teste, classe_teste)
resultado

5/5 [==============================] - 0s 2ms/step - loss: 0.3312 - binary_accuracy: 0.9161


[0.3311608135700226, 0.9160839319229126]